# -*- coding: utf-8 -*-
"""OCR_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNsluo0PU8wm9Rt3uXdc8f_WGkic5aqc

https://www.youtube.com/watch?v=fswR5cbmq-c&t=1034s
"""

import cv2

img = cv2.imread("passport.jpg")

from google.colab.patches import cv2_imshow

cv2_imshow(img)

import requests
import numpy as np

url_api = "https://api.ocr.space/parse/image"
import io

_ , compimg = cv2.imencode(".jpg",img,[1,90])
file_bytes = io.BytesIO(compimg)

result = requests.post(url_api,files={"passport.jpg" : file_bytes},data={"apikey":"e647b4847d88957"})
print(result)

print(result.content.decode())

import json
result = result.content.decode()
result = json.loads(result)

print(result)

text = result.get('ParsedResults')[0].get('ParsedText')

print(text)